name    'rootsh'
version '0.1.0'
source 'https://github.com/juliengk/puppet-module-rootsh'
author 'Julien K'
license 'Apache License, Version 2.0'
summary 'Manage rootsh'
description 'Puppet module for installing and managing rootsh program'
project_page 'https://github.com/juliengk/puppet-module-rootsh'
